---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2025 The Linux Foundation

name: '🛠️ Semantic Pull Request'

# yamllint disable-line rule:truthy
on:
  # Not supported when workflow contains: amannn/action-semantic-pull-request
  # workflow_dispatch:
  pull_request:
    types: [opened, reopened, edited, synchronize]

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  semantic-pull-request:
    name: "Semantic Pull Request"
    permissions:
      contents: read
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      # Harden the runner used by this workflow
      # yamllint disable-line rule:line-length
      - uses: step-security/harden-runner@6c439dc8bdf85cadbbce9ed30d1c7b959517bc49 # v2.12.2
        with:
          egress-policy: audit

      - name: "Validate pull request title"
        # yamllint disable-line rule:line-length
        uses: amannn/action-semantic-pull-request@fdd4d3ddf614fbcd8c29e4b106d3bbe0cb2c605d # v6.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # Requires the type to be capitalised,
          # but accept any of the standard types
          types: |
            Fix
            Feat
            Chore
            Docs
            Style
            Refactor
            Perf
            Test
            Revert
            CI
            Build
          validateSingleCommit: true
          validateSingleCommitMatchesPrTitle: true
